name: Deploy databases

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "1 */12 * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Setup Database
        run: node index.js
        env:
          TOKEN: ${{ secrets.AHQ_STORE_ACCOUNT_DATA }}
    
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: Database Manager
          author_email: ahqsecret@gmail.com
          message: Refresh Database
          push: true
